name: Deploy using rsync
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rsync
        run: sudo apt install rsync -y
      - name: Copy build
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          rsync -az -e "ssh -p $PORT" ./ $USER@$HOST:$PROJECT_PATH
          ssh $USER@$HOST -p $PORT "cd $PROJECT_PATH && npm ci --ignore-scripts && pm2 restart Overshadow -a"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USER: ${{ secrets.USER }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
